allow_anonymous true
listener 1883
protocol mqtt
persistence true
persistence_location /mosquitto/data/
persistence_file mosquitto.db
retained_persistence true
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information